name: Run Colab Notebook

on:
  schedule:
    - cron: '*/1 * * * *'  # 1분마다 실행

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install nbconvert
        pip install jupyter

    - name: Run Colab Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace example_notebook.ipynb
