name: Run Keyword Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # 매 5분마다 실행

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install selenium gspread oauth2client beautifulsoup4 google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

      - name: Run Keyword Script
        env:
          GDRIVE_SERVICE_ACCOUNT_KEY: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT_KEY" > service_account.json
          python keyword_script.py
